# Generated by Django 6.1 on 2026-08-25 22:47

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher plutôt que supprimer : les inscriptions passées sont conservées.', verbose_name='membre actif')),
            ],
            options={
                'verbose_name': 'membre',
                'verbose_name_plural': 'membres',
                'ordering': ['first_name', 'last_name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name'), name='member_unique_name_ci', violation_error_message='Ce membre existe déjà.')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('title', models.CharField(max_length=160, verbose_name='titre')),
                ('body', models.TextField(help_text='Texte simple. Les sauts de ligne sont conservés, le HTML est échappé.', verbose_name='message')),
                ('published_at', models.DateTimeField(verbose_name='publiée le')),
                ('is_published', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'annonces',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_published_idx')],
            },
        ),
    ]
