# Generated by Django 6.1 on 2026-08-25 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'création'), ('updated', 'modification'), ('deleted', 'suppression'), ('restored', 'restauration')], max_length=16, verbose_name='action')),
                ('label', models.CharField(max_length=220, verbose_name='objet')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='lien')),
                ('detail', models.CharField(blank=True, max_length=300, verbose_name='détail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='le')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.member', verbose_name='membre')),
            ],
            options={
                'verbose_name': 'activité',
                'verbose_name_plural': 'activités',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_recent_idx')],
            },
        ),
    ]
