# Generated by Django 6.1 on 2026-08-25 23:49

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'base_manager_name': 'all_objects', 'ordering': ['-published_at'], 'verbose_name': 'annonce', 'verbose_name_plural': 'annonces'},
        ),
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le'),
        ),
        migrations.AddField(
            model_name='news',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.member', verbose_name='supprimé par'),
        ),
    ]
