# Generated by Django 6.1 on 2026-08-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_news_options_alter_news_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(help_text="Texte riche : gras, italique, listes et liens. Assaini à l'enregistrement.", verbose_name='message'),
        ),
    ]
