# Generated by Django 6.1 on 2026-08-25 22:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='identifiant')),
                ('label', models.CharField(max_length=64, verbose_name='libellé')),
                ('color', models.CharField(default='#6c757d', help_text='Code hexadécimal, par exemple #3399cc.', max_length=7, verbose_name='couleur')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'discipline',
                'verbose_name_plural': 'disciplines',
                'ordering': ['position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('label', models.CharField(max_length=64, unique=True, verbose_name='libellé')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='proposé aux membres')),
            ],
            options={
                'verbose_name': "critère d'évaluation",
                'verbose_name_plural': "critères d'évaluation",
                'ordering': ['position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='identifiant')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('department', models.CharField(blank=True, help_text='Code, par exemple 75 ou 2A.', max_length=8, verbose_name='département')),
                ('website', models.URLField(blank=True, max_length=300, verbose_name='site officiel')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.discipline', verbose_name='discipline')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('date_start', models.DateField(verbose_name='date de début')),
                ('date_end', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmée'), ('provisional', 'À confirmer'), ('canceled', 'Annulée')], default='confirmed', max_length=16, verbose_name='statut')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('registration_url', models.URLField(blank=True, max_length=300, verbose_name="lien d'inscription")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='events.event', verbose_name='course')),
            ],
            options={
                'verbose_name': 'édition',
                'verbose_name_plural': 'éditions',
                'ordering': ['date_start', 'event__name'],
            },
        ),
        migrations.CreateModel(
            name='EventFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=60, verbose_name='nom')),
                ('distance', models.CharField(blank=True, help_text='Par exemple : 1,5 km / 40 km / 10 km.', max_length=120, verbose_name='distances')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name="ordre d'affichage")),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='events.eventedition', verbose_name='édition')),
            ],
            options={
                'verbose_name': 'format',
                'verbose_name_plural': 'formats',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='events.eventedition', verbose_name='édition')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.member', verbose_name='membre')),
            ],
            options={
                'verbose_name': 'évaluation',
                'verbose_name_plural': 'évaluations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='events.feedbackcriterion', verbose_name='critère')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='events.feedback', verbose_name='évaluation')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['criterion__position'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('status', models.CharField(choices=[('registered', 'Inscrit'), ('interested', 'Intéressé')], default='registered', max_length=16, verbose_name='statut')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.eventedition', verbose_name='édition')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='events.eventformat', verbose_name='format')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.member', verbose_name='membre')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['edition__date_start', 'member__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name'], name='event_name_idx'),
        ),
        migrations.AddIndex(
            model_name='eventedition',
            index=models.Index(fields=['date_start'], name='edition_date_start_idx'),
        ),
        migrations.AddIndex(
            model_name='eventedition',
            index=models.Index(fields=['status', 'date_start'], name='edition_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventedition',
            constraint=models.UniqueConstraint(fields=('event', 'date_start'), name='edition_unique_event_date', violation_error_message='Cette course a déjà une édition à cette date.'),
        ),
        migrations.AddConstraint(
            model_name='eventedition',
            constraint=models.CheckConstraint(condition=models.Q(('date_end__gte', models.F('date_start'))), name='edition_dates_ordered', violation_error_message='La date de fin ne peut pas précéder la date de début.'),
        ),
        migrations.AddConstraint(
            model_name='eventformat',
            constraint=models.UniqueConstraint(fields=('edition', 'name'), name='format_unique_per_edition', violation_error_message='Ce format existe déjà sur cette édition.'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('member', 'edition'), name='feedback_unique_member_edition', violation_error_message='Ce membre a déjà évalué cette édition.'),
        ),
        migrations.AddConstraint(
            model_name='feedbackscore',
            constraint=models.UniqueConstraint(fields=('feedback', 'criterion'), name='score_unique_per_criterion', violation_error_message='Ce critère est déjà noté dans cette évaluation.'),
        ),
        migrations.AddConstraint(
            model_name='feedbackscore',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='score_between_1_and_5', violation_error_message='La note doit être comprise entre 1 et 5.'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['member', 'status'], name='participation_member_idx'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('member', 'edition'), name='participation_unique_member_edition', violation_error_message='Ce membre est déjà inscrit à cette édition.'),
        ),
    ]
