# Generated by Django 6.1 on 2026-08-25 23:18

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'base_manager_name': 'all_objects', 'ordering': ['name'], 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='eventedition',
            options={'base_manager_name': 'all_objects', 'ordering': ['date_start', 'event__name'], 'verbose_name': 'édition', 'verbose_name_plural': 'éditions'},
        ),
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='eventedition',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le'),
        ),
        migrations.AddField(
            model_name='event',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.member', verbose_name='supprimé par'),
        ),
        migrations.AddField(
            model_name='eventedition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le'),
        ),
        migrations.AddField(
            model_name='eventedition',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.member', verbose_name='supprimé par'),
        ),
    ]
