# Generated by Django 6.1 on 2026-08-25 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_news_options_alter_news_managers_and_more'),
        ('events', '0002_alter_event_options_alter_eventedition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('year', models.PositiveSmallIntegerField(verbose_name='année')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='events.event', verbose_name='course')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.member', verbose_name='écartée par')),
            ],
            options={
                'verbose_name': 'proposition écartée',
                'verbose_name_plural': 'propositions écartées',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'year'), name='dismissal_unique_event_year', violation_error_message='Cette proposition est déjà écartée.')],
            },
        ),
    ]
